export type RootStackParamList = {
  Main: undefined;  
  SignIn: undefined;
  SignUp: undefined;
  ForgotPassword: undefined;
  Settings: undefined; 
  About: undefined;
  Crossword: undefined;
  WordSearch: undefined;
  VideoRecorder: undefined;
  Family: undefined;
  FamilyModule: { moduleNumber: number };
  Friends: undefined;
  FriendsModule: { moduleNumber: number };
  Animals: undefined;
  AnimalsModule: { moduleNumber: number };
  Fruits: undefined;
  FruitsModule: { moduleNumber: number };
  Saudation: undefined;
  Notifications: undefined;
};